AWSTemplateFormatVersion: 2010-09-09
Resources:
  EventNotificationBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: poc-event-notification-lambda

  DocumentsFolder:
    Type: AWS::S3::Bucket::Object
    Properties:
      Bucket: !Ref EventNotificationBucket
      Key: documents/
      ContentType: application/vnd.amazon.ebook

  SheetsFolder:
    Type: AWS::S3::Bucket::Object
    Properties:
      Bucket: !Ref EventNotificationBucket
      Key: sheets/
      ContentType: application/vnd.amazon.ebook