AWSTemplateFormatVersion: 2010-09-09
Resources:
  EventNotificationBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      Tags:
      - Key: environment
        Value: dev
      - Key: application
        Value: lambda-event-notification-poc
      LifecycleConfiguration:
        Rules:
          - Id: DeleteObjectsAfter30Days
            Status: Enabled
            ExpirationInDays: 30
      NotificationConfiguration:
        Event: 's3:ObjectCreated:*'
        Function: 'arn:aws:lambda:us-east-1:552100639279:function:lambda-event-notification-poc'