AWSTemplateFormatVersion: 2010-09-09
Resources:
  EventNotificationBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: poc-s3-event-notification-files
      NotificationConfiguration:
        Event: 's3:ObjectCreated:*'
        Function: <<lambda-arn-here>>
