name: Lambda Event Notification Deploy
on:
  push:
    branches: [ master, main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: npm install --no-cache
        
      - name: Build
        run: npm run build

      - name: Move node_modules to dist
        run: mv node_modules lambda/dist/node_modules

      - name: Zip
        run: (cd lambda/dist && zip -r ../lambda.zip .)

      - name: Deploying lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: lambda-event-notification-poc
          zip_file: lambda.zip